### ISSUE TITLE
  mysql_node/0.1-dev: Compile Package Failure (exit code: 1)  

### ISSUE THREAD

**Issue by wulonghui** [cloudfoundry-community-attic/cf-services-release#22]
Error 450001: Compile Package Failure (exit code: 1)
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/bosh_agent-1.5.0.pre.3/lib/bosh_agent/message/compile_package.rb:206:in `block in compile'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/bosh_agent-1.5.0.pre.3/lib/bosh_agent/message/compile_package.rb:190:in`chdir'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/bosh_agent-1.5.0.pre.3/lib/bosh_agent/message/compile_package.rb:190:in `compile'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/bosh_agent-1.5.0.pre.3/lib/bosh_agent/message/compile_package.rb:64:in`start'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/bosh_agent-1.5.0.pre.3/lib/bosh_agent/message/compile_package.rb:31:in `process'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/bosh_agent-1.5.0.pre.3/lib/bosh_agent/handler.rb:277:in`process'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/bosh_agent-1.5.0.pre.3/lib/bosh_agent/handler.rb:262:in `process_long_running'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/bosh_agent-1.5.0.pre.3/lib/bosh_agent/handler.rb:189:in`block in process_in_thread'
internal:prelude:10:in `synchronize'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/bosh_agent-1.5.0.pre.3/lib/bosh_agent/handler.rb:187:in`process_in_thread'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/bosh_agent-1.5.0.pre.3/lib/bosh_agent/handler.rb:167:in `block in handle_message'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:1060:in`call'
/var/vcap/bosh/lib/ruby/gems/1.9.1/gems/eventmachine-0.12.10/lib/eventmachine.rb:1060:in `block in spawn_threadpool'
- set -e
- cp -a common mysql_service packaging pkg_utils warden /var/vcap/packages/mysql_node
- cd /var/vcap/packages/mysql_node/mysql_service
- /var/vcap/packages/ruby/bin/bundle config build.do_sqlite3 --with-sqlite3-dir=/var/vcap/packages/sqlite
- /var/vcap/packages/ruby/bin/bundle config build.mysql2 --with-mysql-dir=/var/vcap/packages/mysqlclient --with-mysql-include=/var/vcap/packages/mysqlclient/include/mysql
- /var/vcap/packages/ruby/bin/bundle config build.do_mysql --with-mysql-dir=/var/vcap/packages/mysqlclient --with-mysql-include=/var/vcap/packages/mysqlclient/include/mysql
- /var/vcap/packages/ruby/bin/bundle install --local --deployment
  Installing rake (10.1.0) 
  Installing i18n (0.6.4) 
  Installing multi_json (1.7.7) 
  Installing activesupport (3.2.14) 
  Installing addressable (2.3.5) 
  Installing backports (3.3.3) 
  Installing bcrypt-ruby (3.1.1) with native extensions 
  Installing beefcake (0.3.7) 
  Installing builder (3.2.2) 
  Installing cf-uaa-lib (1.3.10) 
  Installing ci_reporter (1.6.4) 
  Installing cookiejar (0.3.0) 
  Installing curb (0.7.18) with native extensions 
  Installing daemons (1.1.9) 
  Installing dm-core (1.2.1) 
  Installing dm-aggregates (1.2.0) 
  Installing dm-constraints (1.2.0) 
  Installing dm-migrations (1.2.0) 
  Installing fastercsv (1.5.5) 
  Installing json (1.8.0) with native extensions 
  Installing json_pure (1.8.0) 
  Installing dm-serializer (1.2.2) 
  Installing dm-timestamps (1.2.0) 
  Installing dm-transactions (1.2.0) 
  Installing stringex (1.5.1) 
  Installing uuidtools (2.1.4) 
  Installing dm-types (1.2.2) 
  Installing dm-validations (1.2.0) 
  Installing data_mapper (1.2.0) 
  Installing data_objects (0.10.13) 
  Installing datamapper (1.2.0) 
  Installing descendants_tracker (0.0.1) 
  Installing diff-lcs (1.2.2) 
  Installing dm-do-adapter (1.2.0) 
  Installing do_mysql (0.10.13) with native extensions 
  Installing dm-mysql-adapter (1.2.0) 
  Installing do_sqlite3 (0.10.13) with native extensions 
  Installing dm-sqlite-adapter (1.2.0) 
  Installing eventmachine (1.0.3) with native extensions 
  Installing em-socksify (0.3.0) 
  Installing http_parser.rb (0.6.0.beta.2) with native extensions 
  Installing em-http-request (1.1.0) 
  Installing eventmachine_httpserver (0.2.1) with native extensions 
  Installing msgpack (0.5.5) with native extensions 
  Installing yajl-ruby (1.1.0) with native extensions 
  Installing fluent-logger (0.4.6) 
  Installing hashie (2.0.5) 
  Installing multi_xml (0.5.4) 
  Installing rack (1.5.2) 
  Installing rack-accept (0.4.5) 
  Installing rack-mount (0.8.3) 
  Installing virtus (0.5.5) 
  Installing grape (0.5.0) 
  Installing httpclient (2.3.4.1) 
  Installing membrane (0.0.2) 
  Installing mime-types (1.23) 
  Installing mono_logger (1.1.0) 
  Installing multipart-post (1.2.0) 
  Installing mysql2 (0.3.11) with native extensions 
  Installing thin (1.5.1) with native extensions 
  Installing nats (0.4.26) 
  Installing posix-spawn (0.3.6) with native extensions 
  Installing rack-protection (1.5.0) 
  Installing redis (3.0.4) 
  Installing redis-namespace (1.3.0) 
  Installing tilt (1.4.1) 
  Installing sinatra (1.4.3) 
  Installing vegas (0.1.11) 
  Installing resque (1.24.1) 
  Installing resque-status (0.4.1) 
  Installing rspec-core (2.13.1) 
  Installing rspec-expectations (2.13.0) 
  Installing rspec-mocks (2.13.1) 
  Installing rspec (2.13.0) 
  Installing ruby-hmac (0.4.0) 
  Installing rubyzip (0.9.9) 
  Installing sequel (3.45.0) 
  Installing squash_ruby (1.2.0) 
  Installing steno (1.1.0) 
  Installing vmstat (2.0.0) with native extensions 
  Installing vcap_common (2.2.1) 
  Installing vcap_logging (1.0.2) 
  Installing warden-protocol (0.0.9) 
  Installing warden-client (0.0.7) 
  Installing vcap_services_base (0.1.17) 
  Using bundler (1.2.1) 
  Updating files in vendor/cache
  Your bundle is complete! It was installed into ./vendor/bundle
- cd /var/vcap/packages/mysql_node/warden
- /var/vcap/packages/ruby/bin/bundle install --local --deployment --without=development test
  Could not read gem at /var/vcap/data/packages/mysql_node/0.1-dev.1/warden/vendor/cache/eventmachine-1.0.0.gem. It may be corrupted.

---

I used the lastest relese,Can anybody tell me why?

**Comment by drnic** [comment]
There are git submodules for this repo; try the following:

git submodule update --init
bosh create release
bosh upload release
bosh deploy

**Comment by d00000000000000000000000** [comment]
@drnic where are the git submodules ?

**Comment by d00000000000000000000000** [comment]
@drnic  I want to deploy mysql service for cf v2, is there another repo?
